### ISSUE TITLE
cluster is created on digital ocean but fleetctl shows failed getting response 

### ISSUE THREAD

**Issue by ainux4mrvce** [alexanderkiel/lens-warehouse#13]
coreos@deis ~$  fleetctl list-units

2015/05/29 13:20:12 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:12 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 100ms
2015/05/29 13:20:12 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:12 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 200ms
2015/05/29 13:20:12 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:12 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 400ms
2015/05/29 13:20:12 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:12 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 800ms
2015/05/29 13:20:13 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:13 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 1s
2015/05/29 13:20:14 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:14 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/machines}, retrying in 1s
2015/05/29 13:20:15 ERROR fleetctl.go:212: error attempting to check latest fleet version in Registry: timeout reached
2015/05/29 13:20:15 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:15 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 100ms
2015/05/29 13:20:15 INFO client.go:291: Failed getting response from http://127.0.0.1:4001/: dial tcp 127.0.0.1:4001: connection refused
2015/05/29 13:20:15 ERROR client.go:213: Unable to get result for {Get /_coreos.com/fleet/states}, retrying in 200ms

**Comment by alexanderkiel** [comment]
Is this issue supposed for lens-warehouse or for deis?

**Comment by alexanderkiel** [comment]
I'll close this because it's probably misplaced.
